language: go

services:
  - docker

go:
  - 1.9.x

before_install:

jobs:
  include:
    - stage: test binary
      script: make build_fresh
    - stage: push container
      script: make deploy_quay

after_success:
  - bash <(curl -s https://codecov.io/bash)