language: go

services:
  - docker

go:
  - 1.10.x

before_install:

jobs:
  include:
    - stage: test binary
      script:
        - make build_fresh
        - bash <(curl -s https://codecov.io/bash)
    - stage: push container
      script:
        - make init
        - make update
        - make compile
        - make deploy_quay

after_success: