[server]
port = "3000"
host = "http://localhost:3000"

[oauth2]
id = "testOauth2ID"
secret = "testOauth2Secret"

[database]
name = "passportTest"
user = "passportTest"
password = "passportTest"
host = "localhost"
port = 5432
maxPoolSize = 10