SERVER_HOST: "http://localhost:3000"
SERVER_PORT: "3000"
OAUTH_ID: "testOauth2ID"
OAUTH_SECRET: "testOauth2Secret"
DB_HOST: "localhost"
DB_PORT: 5432
DB_NAME: "passportTest"
DB_USER: "passportTest"
DB_PASSWORD: "passportTest"
DB_MAX_POOL_SIZE: 10