[application]
fileStore = "googlecloud"

[server]
port = "3000"
enableStaticFileServer = false
enableGzipCompression = true
enableDelayMiddleware = false

[database]
name = "tanker"
user = "tanker"
password = "tanker"
host = "localhost"
port = 5432
maxPoolSize = 10

[googlecloud]
jsonConfig = "/Users/sudhanshu/code/private/flying-monkey-club-1483.json"
bucket = "shrieking-cat"
